version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: 'db'
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_rsm
